config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
                                    confirmations: "users/confirmations",
                                    passwords: "users/passwords",
                                    registrations: "users/registrations" }
  resources :users
  resources :articles
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  resourcify
  belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.slim
= simple_form_for(@article) do |f|

  .form-inputs
    = f.input :title
    = f.input :body

  .form-actions
    = f.button :submit

app/views/articles/edit.html.slim
h3 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
= link_to 'New Article', new_article_path, class: 'btn btn-default btn-sm'
br

- @articles.each do |article|
  .article
    h3 = article.title
    p = article.body
    - if article.user
      b = image_tag article.user.avatar.url(:thumb)
      br
      = "by "
      b = article.user.name ? article.user.name : "(no name)"

    br
    p
      i = article.updated_at.strftime("%d.%m. %Y")

    = link_to 'Show', article
    - if current_user && (current_user == article.user || current_user.has_role?(:admin))
      '|
      = link_to 'Edit', edit_article_path(article)
      '|
      = link_to 'Destroy', article_path(article), data: {:confirm => 'Are you sure?'}, :method => :delete
    hr

app/views/articles/new.html.slim
h3 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
h2 = @article.title

p.well
  = @article.body

- if @article.user
  b = image_tag @article.user.avatar.url(:thumb)
  br
  = "by "
  b = @article.user.name ? @article.user.name : "(no name)"

br
p
  i = "last update "
  i = @article.updated_at.strftime("%d.%m. %Y")

hr
- if current_user == @article.user
  = link_to 'Edit', edit_article_path(@article)
  '|
  = link_to 'Destroy', article_path(@article), data: {:confirm => 'Are you sure?'}, :method => :delete