config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions",
                                    confirmations: "users/confirmations",
                                    passwords: "users/passwords",
                                    registrations: "users/registrations" }
  resources :users
  resources :articles
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  root 'articles#index'

end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1"
    title RailsGems

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container

      .pull-left
        h1
          = link_to 'Bloggah', root_path
        = link_to 'Improvised mailbox for testing', '/letter_opener'
      .pull-right
        - if user_signed_in?
          b = "Welcome back, "
          - if current_user.name && !current_user.name.empty?
            b = link_to current_user.name, user_path(current_user)
          - else
            b = link_to current_user.email, user_path(current_user)
          b = "! Want to "
          b = link_to 'logout', destroy_user_session_path, method: :delete
          b = "?"
        - else
          b = "Please "
          b = link_to 'log in', new_user_session_path
          b = " or "
          b = link_to 'register', new_user_registration_path
          b = " to add articles"
      - if current_user && current_user.has_role?(:admin)
        br
        .pull-right
          b = link_to 'User listing', users_path, class: 'btn btn-default btn-sm'
      .clearfix
      hr

      = bootstrap_flash
      = yield